# Generated by Django 3.0.6 on 2020-07-02 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('room_price', models.PositiveIntegerField()),
                ('smoking_status', models.BooleanField()),
                ('room_rating', models.PositiveIntegerField(default=5)),
                ('room_description', models.CharField(max_length=100)),
                ('number_of_guests', models.PositiveIntegerField()),
                ('show_on_homepage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('room_status', models.CharField(choices=[('a', 'Available'), ('na', 'Not_Available'), ('r', 'Reserved'), ('m', 'Maitenance'), ('o', 'Other')], default='a', max_length=2)),
                ('room_floor', models.PositiveIntegerField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room_type')),
            ],
        ),
    ]
