# Generated by Django 3.0.6 on 2020-08-20 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('room_price', models.PositiveIntegerField()),
                ('smoking_status', models.BooleanField()),
                ('room_rating', models.PositiveIntegerField(default=5)),
                ('room_description', models.CharField(max_length=100)),
                ('number_of_guests', models.PositiveIntegerField()),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('room_img', models.CharField(default='/img/bed-4.jpg', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('service_cost', models.PositiveIntegerField()),
                ('service_availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('room_status', models.CharField(choices=[('available', 'available'), ('booked', 'booked'), ('occupied', 'occupied'), ('out_of_order', 'out Of Order'), ('do_not_disturb', 'do_not_disturb'), ('house_use', 'house_use'), ('newly_checked_in', 'newly_checked_in'), ('status_unclear', 'status_unclear')], default='available', max_length=30)),
                ('room_floor', models.PositiveIntegerField()),
                ('housekeeping_status', models.CharField(default='room_cleaned', max_length=100)),
                ('issue', models.CharField(default='no_issues', max_length=100)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room_type')),
            ],
        ),
    ]
