<<<<<<< HEAD
# Generated by Django 3.0.6 on 2020-06-17 08:28
=======
# Generated by Django 3.0.6 on 2020-06-17 09:15
>>>>>>> 4628cd24a3b5ab6fefd02edcc1a54e7a903523a8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_type',
            name='room_rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
