# Generated by Django 3.0.6 on 2020-07-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('service_cost', models.CharField(choices=[('a', 'Available'), ('na', 'Not_Available'), ('r', 'Reserved'), ('m', 'Maitenance'), ('o', 'Other')], default='a', max_length=2)),
                ('service_availability', models.BooleanField(default=True)),
            ],
        ),
    ]
