# Generated by Django 3.0.6 on 2020-06-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_type_room_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_type',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
