# Generated by Django 3.0.6 on 2020-07-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='services',
        ),
    ]
