# Generated by Django 3.0.6 on 2020-07-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20200716_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_type',
            name='room_img',
            field=models.CharField(default='/bookings/img/bed-3.jpg', max_length=500),
        ),
    ]
