# Generated by Django 3.0.6 on 2020-07-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_room_type_room_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_type',
            name='room_img',
            field=models.CharField(default='/img/bed-4.jpg', max_length=500),
        ),
    ]
