# Generated by Django 3.0.6 on 2020-07-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20200717_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('available', 'available'), ('booked', 'booked'), ('occupied', 'occupied'), ('out_of_order', 'out Of Order'), ('do_not_disturb', 'do_not_disturb'), ('house_use', 'house_use'), ('newly_checked_in', 'newly_checked_in'), ('status_unclear', 'status_unclear')], default='a', max_length=30),
        ),
    ]
