# Generated by Django 3.0.6 on 2020-07-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_room_housekeeping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='issue',
            field=models.CharField(default='no_issues', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='issue_description',
            field=models.TextField(default=''),
        ),
    ]
