# Generated by Django 3.0.6 on 2020-07-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_auto_20200726_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='issue_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
