# Generated by Django 3.0.6 on 2020-08-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phonenumber', models.CharField(max_length=20)),
                ('driver_gender', models.CharField(max_length=10)),
                ('driver_age', models.PositiveIntegerField()),
                ('driver_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=100)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('registered_number', models.CharField(max_length=100)),
                ('vehicle_category', models.CharField(max_length=100)),
                ('vehicle_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('driver_type', models.CharField(max_length=100)),
                ('driver_alloted', models.CharField(max_length=100)),
                ('time_alloted', models.CharField(max_length=100)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
