# Generated by Django 3.0.6 on 2020-08-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveldesk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pick_drop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('pick_location', models.CharField(max_length=100)),
                ('drop_location', models.CharField(max_length=100)),
                ('driver', models.CharField(max_length=100)),
                ('vehicle_category', models.CharField(max_length=100)),
                ('registered_number', models.CharField(max_length=100)),
            ],
        ),
    ]
