# Generated by Django 3.0.6 on 2020-08-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveldesk', '0002_pick_drop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick_drop',
            name='driver',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pick_drop',
            name='drop_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pick_drop',
            name='pick_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pick_drop',
            name='registered_number',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pick_drop',
            name='vehicle_category',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
