# Generated by Django 3.0.6 on 2020-08-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveldesk', '0003_auto_20200813_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick_drop',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
