# Generated by Django 3.0.6 on 2020-08-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveldesk', '0004_pick_drop_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick_drop',
            name='driver',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='pick_drop',
            name='registered_number',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='pick_drop',
            name='vehicle_category',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
