# Generated by Django 3.0.6 on 2020-08-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveldesk', '0005_auto_20200813_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick_drop',
            name='status',
            field=models.CharField(default='unclear', max_length=100),
        ),
    ]
