# Generated by Django 3.0.6 on 2020-08-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveldesk', '0006_pick_drop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick_drop',
            name='time',
            field=models.CharField(default='00:00', max_length=100),
        ),
    ]
