# Generated by Django 3.0.6 on 2020-08-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveldesk', '0007_pick_drop_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick_drop',
            name='time',
            field=models.CharField(default='12:00', max_length=100),
        ),
    ]
