# Generated by Django 3.0.6 on 2020-08-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveldesk', '0008_auto_20200813_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick_drop',
            name='vehicle_category',
            field=models.CharField(default='prime_car', max_length=100),
        ),
    ]
