# Generated by Django 3.0.6 on 2020-06-28 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_account_phonenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Account',
        ),
    ]
