# Generated by Django 3.0.6 on 2020-07-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
