# Generated by Django 3.0.6 on 2020-07-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateField()),
                ('in_time', models.TimeField()),
                ('out_date', models.DateField()),
                ('out_time', models.TimeField()),
                ('room_count', models.PositiveIntegerField()),
                ('guest_count', models.PositiveIntegerField()),
                ('adult_count', models.PositiveIntegerField()),
                ('children_count', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('identification', models.CharField(max_length=50)),
            ],
        ),
    ]
