# Generated by Django 3.0.6 on 2020-08-20 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_guest_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.CharField(max_length=30)),
                ('in_time', models.CharField(max_length=30)),
                ('out_date', models.CharField(max_length=30)),
                ('out_time', models.CharField(max_length=30)),
                ('room_count', models.CharField(default=1, max_length=10)),
                ('guest_count', models.CharField(default=1, max_length=10)),
                ('adult_count', models.CharField(default=1, max_length=20)),
                ('children_count', models.CharField(default=1, max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('identification', models.CharField(max_length=50)),
                ('status', models.CharField(default='closed', max_length=100)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='booking_room_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_details', models.TextField()),
                ('service_details', models.TextField()),
                ('amount', models.CharField(max_length=10)),
                ('payment_type', models.CharField(max_length=20)),
                ('booking_status', models.CharField(max_length=20)),
                ('booking_guest_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking_guest_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('room', models.CharField(max_length=100)),
                ('order_id', models.CharField(default='', max_length=100)),
                ('payment_status', models.CharField(default='', max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('booking_guest_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking_guest_details')),
                ('booking_room_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking_room_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
