# Generated by Django 3.0.6 on 2020-07-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adult_count',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children_count',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='fname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_count',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='identification',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='in_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='in_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='lname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='out_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='out_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phonenumber',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_count',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='town',
            field=models.CharField(default='', max_length=50),
        ),
    ]
