# Generated by Django 3.0.6 on 2020-07-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_room_details',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='', max_length=30),
        ),
    ]
