# Generated by Django 3.0.6 on 2020-07-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20200714_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='in_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='out_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='out_time',
            field=models.TimeField(),
        ),
    ]
