# Generated by Django 3.0.6 on 2020-07-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20200714_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='in_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='in_time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='out_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='out_time',
            field=models.CharField(max_length=30),
        ),
    ]
